apiVersion: v1
kind: Service
metadata:
    name: gatewaytech-service
    labels: 
       app: gatewaytech-app

spec:
    selector: 
       app: gatewaytech-app
    type: NodePort
    ports:
       - nodePort: 31000 
         port: 80
         targetPort: 80
